const metrics=[['leads','线索'],['qualified','有效线索'],['bookings','预约体验'],['attended','到场体验'],['orders','购买订单']];
const fmt=n=>Number.isFinite(n)?Math.round(n).toLocaleString('zh-CN'):'—',pct=n=>Number.isFinite(n)?(n*100).toFixed(2)+'%':'—',signed=n=>(n>0?'+':'')+fmt(n),ratio=(a,b)=>b>0?a/b:null;
const change=(a,b)=>!Number.isFinite(a)||!Number.isFinite(b)?null:b>0?(a-b)/b:null;
const deltaText=(a,b)=>b===0?(a===0?'无变化':'上期为零，不计算变化率'):(change(a,b)>0?'+':'')+pct(change(a,b));
const pp=(a,b)=>a===null||b===null?'不可比':((a-b)>0?'+':'')+((a-b)*100).toFixed(2)+'pp';
const iso=d=>d.toISOString().slice(0,10),day=s=>new Date(s+'T00:00:00Z'),shift=(s,n)=>{const d=day(s);d.setUTCDate(d.getUTCDate()+n);return iso(d)};
function monthStart(s){return s.slice(0,8)+'01'}function priorMonth(s){const d=day(s),n=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-1);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(n,last));return iso(d)}
function sum(rows){const a=Object.fromEntries(['visits','leads','qualified','bookings','attended','orders','revenue_yuan','spend_yuan'].map(k=>[k,0]));for(const r of rows)for(const k in a)a[k]+=r[k];return a}
const section=(n,title,notes,body)=>`<section class="section"><h2><span>0${n}</span>${title}</h2>${notes}${body}</section>`;
const notes=(a,b)=>`<div class="notes"><div class="note"><span>波动数据</span><p>${a}</p></div><div class="note"><span>归因结论</span><p>${b}</p></div></div>`;
const card=(title,body)=>`<div class="card"><h3>${title}</h3>${body}</div>`;
const svgStart=(w,h,label)=>`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${label}">`;
function barChart(items,keys,label){const w=540,h=265,L=42,R=15,T=25,B=55,values=items.flatMap(x=>keys.map(k=>x[k.key])),min=Math.min(0,...values),max=Math.max(1,...values),span=max-min||1,y=v=>T+(max-v)/span*(h-T-B),group=(w-L-R)/items.length,bw=Math.min(25,group/(keys.length+1));let s=svgStart(w,h,label);for(let i=0;i<=4;i++){let v=min+span*i/4;s+=`<line x1="${L}" x2="${w-R}" y1="${y(v)}" y2="${y(v)}" stroke="#edf0f5"/><text x="${L-7}" y="${y(v)+3}" text-anchor="end">${Math.round(v)}</text>`}items.forEach((a,i)=>{keys.forEach((k,j)=>{const v=a[k.key];s+=`<rect class="bar" x="${L+group*i+group/2+(j-keys.length/2)*bw}" y="${Math.min(y(0),y(v))}" width="${bw-3}" height="${Math.max(1,Math.abs(y(v)-y(0)))}" rx="1" fill="${k.color}"><title>${a.name} · ${k.label}：${v.toFixed(2)}${label.includes('环比')?'%':''}</title></rect>`});s+=`<text x="${L+group*i+group/2}" y="${h-24}" text-anchor="middle">${a.name}</text>`});return s+'</svg>'}
function waterfall(cs){let cursor=0;const values=[0];cs.forEach(c=>{cursor+=c.delta;values.push(cursor)});const max=Math.max(1,...values),min=Math.min(0,...values),span=max-min||1,w=540,h=310,L=42,B=60,T=25,y=v=>T+(max-v)/span*(h-T-B),bw=55,g=(w-L-12)/(cs.length+1);let s=svgStart(w,h,'线索渠道增量瀑布图');s+=`<line x1="${L}" x2="${w-12}" y1="${y(0)}" y2="${y(0)}" stroke="#dadfe8"/>`;cs.forEach((c,i)=>{s+=`<rect class="bar" x="${L+i*g+5}" y="${Math.min(y(values[i]),y(values[i+1]))}" width="${bw}" height="${Math.max(1,Math.abs(y(values[i+1])-y(values[i])))}" fill="${c.delta>=0?'#6351bd':'#d36946'}"><title>${c.name}：${signed(c.delta)} 条</title></rect><text x="${L+i*g+g/2}" y="${Math.min(y(values[i]),y(values[i+1]))-6}" text-anchor="middle">${signed(c.delta)}</text><text transform="translate(${L+i*g+g/2},${h-35}) rotate(-25)" text-anchor="middle">${c.name}</text>`});s+=`<rect x="${L+cs.length*g+5}" y="${Math.min(y(0),y(cursor))}" width="${bw}" height="${Math.max(1,Math.abs(y(cursor)-y(0)))}" fill="#333944"><title>净增量 ${signed(cursor)}</title></rect><text x="${L+cs.length*g+g/2}" y="${h-35}" text-anchor="middle">净增量</text>`;return s+'</svg>'}
function horizontal(cs){const w=540,h=310,L=90,R=55,T=20,g=42,max=Math.max(1,...cs.map(c=>Math.abs(c.delta))),x=v=>L+175+v/max*150;let s=svgStart(w,h,'各渠道线索增减量');s+=`<line x1="${x(0)}" x2="${x(0)}" y1="8" y2="${h-30}" stroke="#ddd"/>`;cs.forEach((c,i)=>{const yy=T+i*g;s+=`<text x="${L-7}" y="${yy+16}" text-anchor="end">${c.name}</text><rect class="bar" x="${Math.min(x(0),x(c.delta))}" y="${yy}" width="${Math.max(1,Math.abs(x(c.delta)-x(0)))}" height="25" fill="${c.delta>=0?'#259c7c':'#d36946'}"><title>${c.name}：${signed(c.delta)}；环比 ${deltaText(c.cur.leads,c.prev.leads)}</title></rect><text x="${x(c.delta)+(c.delta>=0?5:-5)}" y="${yy+16}" text-anchor="${c.delta>=0?'start':'end'}">${signed(c.delta)}</text>`});return s+'</svg>'}
function dualChart(cs){const w=1080,h=255,L=50,R=48,T=25,B=45,maxA=Math.max(1,...cs.map(c=>Math.abs(c.cur.attended-c.prev.attended))),maxO=Math.max(1,...cs.map(c=>Math.abs(c.cur.orders-c.prev.orders))),mid=130,scaleA=85/maxA,scaleO=85/maxO,g=(w-L-R)/cs.length;let s=svgStart(w,h,'到场与订单增量对比，左右轴分别表示人数与订单数');s+=`<line x1="${L}" x2="${w-R}" y1="${mid}" y2="${mid}" stroke="#ddd"/><text x="${L}" y="14">到场增量（左轴）</text><text x="${w-R}" y="14" text-anchor="end">订单增量（右轴）</text>`;for(let i=-2;i<=2;i++){s+=`<text x="${L-8}" y="${mid-i*42.5}" text-anchor="end">${fmt(maxA*i/2)}</text><text x="${w-R+8}" y="${mid-i*42.5}">${fmt(maxO*i/2)}</text>`}cs.forEach((c,i)=>{const a=c.cur.attended-c.prev.attended,o=c.cur.orders-c.prev.orders,x=L+i*g+g/2;s+=`<rect class="bar" x="${x-30}" y="${a>=0?mid-a*scaleA:mid}" width="27" height="${Math.max(1,Math.abs(a*scaleA))}" fill="#6351bd"><title>${c.name} 到场增量 ${signed(a)}</title></rect><rect class="bar" x="${x+3}" y="${o>=0?mid-o*scaleO:mid}" width="27" height="${Math.max(1,Math.abs(o*scaleO))}" fill="#d36946"><title>${c.name} 订单增量 ${signed(o)}</title></rect><text x="${x}" y="${h-8}" text-anchor="middle">${c.name}</text>`});return s+'</svg>'}
function trendChart(series){const w=1080,h=270,L=50,R=20,T=25,B=40,keys=[['leads','线索','#6552c2'],['attended','到场','#2b9b80'],['orders','订单','#d36d47']],points=keys.map(([k])=>series.map(r=>ratio(r.v[k],series[0].v[k])===null?null:r.v[k]/series[0].v[k]*100)),max=Math.max(120,...points.flat().filter(Number.isFinite)),y=v=>T+(max-v)/max*(h-T-B),x=i=>L+i*(w-L-R)/(series.length-1||1);let s=svgStart(w,h,'连续八周趋势，首周等于100');for(let v=0;v<=max;v+=25)s+=`<line x1="${L}" x2="${w-R}" y1="${y(v)}" y2="${y(v)}" stroke="#eef0f6"/><text x="${L-8}" y="${y(v)+3}" text-anchor="end">${v}</text>`;series.forEach((r,i)=>s+=`<text x="${x(i)}" y="${h-13}" text-anchor="middle">${r.date.slice(5)}</text>`);keys.forEach(([k,title,color],j)=>{let valid=points[j].map((v,i)=>({v,i})).filter(p=>p.v!==null);s+=`<polyline points="${valid.map(p=>x(p.i)+','+y(p.v)).join(' ')}" fill="none" stroke="${color}" stroke-width="2"/>`;valid.forEach(p=>s+=`<circle cx="${x(p.i)}" cy="${y(p.v)}" r="3" fill="${color}"><title>${series[p.i].date} ${title}：${fmt(series[p.i].v[k])}，指数 ${p.v.toFixed(1)}</title></circle>`)});return s+'</svg>'}
let source;const content=document.querySelector('#report-content');
async function init(){try{const r=await fetch('assets/business-data.json');if(!r.ok)throw Error('读取失败');source=await r.json();if(source.simulated!==true)throw Error('数据未标识为模拟');const cut=document.querySelector('#cutoff');for(let d=source.cutoff;d>='2026-05-31';d=shift(d,-7))cut.add(new Option(d,d));document.querySelector('#brand').onchange=render;cut.onchange=render;render()}catch(e){content.innerHTML='<p class="notice">暂时无法读取模拟报告。请刷新重试，或使用顶部入口下载 CSV。</p>'}}
function calculate(data,brand,end){const records=data.rows.filter(r=>brand==='all'||r.brand===brand),beg=monthStart(end),last=priorMonth(end),lastBeg=monthStart(last);const between=(a,b)=>records.filter(r=>r.date>=a&&r.date<=b);const currentRows=between(beg,end),prevRows=between(lastBeg,last),keys=['visits',...metrics.map(m=>m[0]),'revenue_yuan','spend_yuan'];const invalid=records.some(r=>keys.some(k=>!Number.isFinite(r[k])||r[k]<0));let missing=false;for(const [a,b] of [[beg,end],[lastBeg,last],[shift(end,-13),end]]){const count=between(a,b).length,expected=(Math.round((day(b)-day(a))/86400000)+1)*6*(brand==='all'?2:1);if(count!==expected)missing=true}if(invalid||missing)return{error:'本次选择的数据缺失或字段无效，已停止计算。缺失不按零处理。'};const cur=sum(currentRows),prev=sum(prevRows),week=sum(between(shift(end,-6),end)),oldWeek=sum(between(shift(end,-13),shift(end,-7))),channels=[...new Set(records.map(r=>r.channel))];const cs=channels.map(name=>{const c=sum(currentRows.filter(r=>r.channel===name)),p=sum(prevRows.filter(r=>r.channel===name));return{name,cur:c,prev:p,delta:c.leads-p.leads}});const trend=[];for(let i=7;i>=0;i--){let e=shift(end,-7*i);trend.push({date:e,v:sum(between(shift(e,-6),e))})}return{beg,last,lastBeg,cur,prev,week,oldWeek,cs,trend}}
function render(){const brand=document.querySelector('#brand').value,end=document.querySelector('#cutoff').value,d=calculate(source,brand,end);if(d.error){content.innerHTML=`<p class="notice">${d.error}</p>`;return}const{beg,last,lastBeg,cur,prev,week,oldWeek,cs,trend}=d;document.querySelector('#range').textContent=`统计周 ${shift(end,-6)} 至 ${end} ｜ MTD ${beg} 至 ${end}，对比 ${lastBeg} 至 ${last} ｜ ${brand==='all'?'两品牌合计':brand} / 模拟体验服务业务`;
const conv=ratio(cur.orders,cur.attended),oldConv=ratio(prev.orders,prev.attended),leadDelta=cur.leads-prev.leads,orderDelta=cur.orders-prev.orders,sorted=[...cs].sort((a,b)=>b.delta-a.delta),top=sorted[0],low=sorted.at(-1),contrib=ratio(top.delta,Math.abs(leadDelta)),modelGap=oldConv===null?null:cur.attended*oldConv-cur.orders;
const metricRows=metrics.map(([k,t])=>`<div class="metric-row"><span>${t}</span><b>${fmt(cur[k])}</b><small class="${cur[k]>=prev[k]?'good':'bad'}">${deltaText(cur[k],prev[k])}</small></div>`).join('');
const cards=[['到场 → 购买转化率',`${pct(oldConv)} → ${pct(conv)}`,`${pp(conv,oldConv)}；分母为当期到场量`,'bad'],[modelGap>=0?'按上期转化率估算的订单缺口':'按上期转化率估算的订单增益',modelGap===null?'不可比':fmt(Math.abs(modelGap))+' 单','固定本期到场量的估算，不等于可追回订单','purple'],['最大正向渠道贡献',leadDelta===0?'不适用':pct(contrib),`${top.name}；分母为净增量绝对值`,'purple'],['线索 → 购买转化率',`${pct(ratio(prev.orders,prev.leads))} → ${pct(ratio(cur.orders,cur.leads))}`,`本期 ${fmt(cur.orders)} 单 / ${fmt(cur.leads)} 条线索`,'good']];
content.innerHTML=`<div class="summary"><b>一句话判断：</b>MTD 线索 ${deltaText(cur.leads,prev.leads)}，订单 ${deltaText(cur.orders,prev.orders)}。到场购买率由 ${pct(oldConv)} 变为 ${pct(conv)}；先拆解渠道结构，再验证体验后的转化承接。所有结论均基于模拟数据。</div><div class="kpis">${cards.map(([a,b,c,cls])=>`<article class="kpi"><small>${a}</small><b class="${cls}">${b}</b><p>${c}</p></article>`).join('')}</div>`;
content.innerHTML+=section(1,'整体表现：规模与转化，一起看',notes(`MTD 获得线索 <b>${fmt(cur.leads)}</b>（${deltaText(cur.leads,prev.leads)}），到场 <b>${fmt(cur.attended)}</b>（${deltaText(cur.attended,prev.attended)}），购买 <b>${fmt(cur.orders)}</b>（${deltaText(cur.orders,prev.orders)}）。`,`规模变化与转化效率需要分开判断。到场购买率变化 ${pp(conv,oldConv)}；下面继续拆解渠道，区分新增规模与购买贡献。`),`<div class="two">${card('MTD 漏斗结果 · 量与环比',metricRows+`<div class="callout red">当前到场购买率 ${pct(conv)}；按上期转化率套用本期到场量，估算订单 ${fmt(oldConv===null?NaN:cur.attended*oldConv)}，实际 ${fmt(cur.orders)}。该差额仅用于定位量级。</div>`)}${card('关键指标环比 · MTD 与当周',`<div class="legend"><span><i></i>MTD 同期</span><span><i class="green"></i>完整周环比</span></div>`+barChart(metrics.map(([k,name])=>({name,a:(change(cur[k],prev[k])||0)*100,b:(change(week[k],oldWeek[k])||0)*100})),[{key:'a',label:'MTD环比',color:'#6351bd'},{key:'b',label:'周环比',color:'#28a382'}],'指标环比')+`<div class="callout">周度与 MTD 的统计窗口不同，不直接相减。零基数变化率不适用，图形以零位占位，真实情况见表格与文字。</div>`)}</div>`);
const events=source.events.filter(e=>e.date>=beg&&e.date<=end);const evidence=events.length?events.map(e=>e.event+' '+e.evidence).join(' '):'当前周期无对应的模拟活动记录，变化原因待验证；不将渠道相关性直接表述为因果。';
content.innerHTML+=section(2,'增长结构：增量来自哪里',notes(`MTD 线索净变化 <b>${signed(leadDelta)}</b>。${top.name}贡献 ${signed(top.delta)}，${low.name}贡献 ${signed(low.delta)}。`,`可确认的是渠道对总增量的算术贡献。${evidence}`),`<div class="two">${card('线索渠道增量瀑布图 · 本月 MTD − 上月同期',waterfall(sorted)+`<div class="callout">六个渠道增减量之和 = ${signed(leadDelta)}。净增量为零时不计算贡献率；贡献超过 100% 表示其他渠道有抵消。</div>`)}${card('各渠道线索增减量 · 同期比较',horizontal(cs)+`<div class="callout warm">优先核对 ${top.name} 的客群结构与 ${low.name} 的渠道活动记录，再决定是否扩大或恢复投入。</div>`)}</div>`);
const table=`<div class="table-scroll"><table><thead><tr><th>渠道</th><th>到场</th><th>到场增量</th><th>订单</th><th>订单增量</th><th>到场购买率</th></tr></thead><tbody>${cs.map(c=>`<tr><td>${c.name}</td><td>${fmt(c.cur.attended)}</td><td>${signed(c.cur.attended-c.prev.attended)}</td><td>${fmt(c.cur.orders)}</td><td>${signed(c.cur.orders-c.prev.orders)}</td><td>${pct(ratio(c.cur.orders,c.cur.attended))}</td></tr>`).join('')}</tbody></table></div>`;
const weak=[...cs].filter(c=>c.cur.attended>0).sort((a,b)=>a.cur.orders/a.cur.attended-b.cur.orders/b.cur.attended)[0];
content.innerHTML+=section(3,'断点定位：增长与购买是否来自同一渠道',notes(`到场变化 ${signed(cur.attended-prev.attended)}，订单变化 ${signed(orderDelta)}。${weak?weak.name:'暂无有效渠道'} 的到场购买率${weak?'为 '+pct(ratio(weak.cur.orders,weak.cur.attended)):'不可计算'}。`,`把到场增量和订单增量并列观察，可以定位规模与结果的差异。低转化只用于定位问题；原因还需验证用户需求、跟进时效和产品匹配。`),card('到场增量 vs 订单增量 · 左右轴分别为人数和订单数',`<div class="legend"><span><i></i>到场增量（左轴）</span><span><i class="orange"></i>订单增量（右轴）</span></div>`+dualChart(cs)+table));
content.innerHTML+=section(4,'趋势验证：是单周波动，还是持续变化',notes(`本周线索 ${fmt(week.leads)}（${deltaText(week.leads,oldWeek.leads)}），到场 ${fmt(week.attended)}（${deltaText(week.attended,oldWeek.attended)}），订单 ${fmt(week.orders)}（${deltaText(week.orders,oldWeek.orders)}）。`,`将连续八个完整周归一化到首周 = 100，观察规模和购买走势是否同步。指数反映相对变化，不用于比较不同指标的绝对规模。`),card('连续八周趋势 · 各指标首周 = 100',`<div class="legend"><span><i></i>线索</span><span><i class="green"></i>到场</span><span><i class="orange"></i>订单</span></div>`+trendChart(trend)+`<div class="events">活动记录：${events.length?events.map(e=>e.date+' · '+e.event).join(' ｜ '):'当前周期暂无模拟活动记录。'} 首周基数为零的序列不计算指数。</div>`));
const actions=[['P0','转化','优先验证体验后的购买承接',`到场购买率 ${pct(oldConv)} → ${pct(conv)}，变化 ${pp(conv,oldConv)}。`,`${weak?weak.name:'有效渠道待补充'} 转化较低；先比较客群结构与跟进记录。`,modelGap===null?'上期无有效基数，不估算。':`固定本期到场量的模型差额为 ${fmt(Math.abs(modelGap))} 单；不作为已实现损失或收益。`,'按渠道抽样复核用户需求、跟进时效与未购买原因，下一周按同口径追踪。'],['P0','结构','检验增量来源与集中风险',`${top.name} 线索增量 ${signed(top.delta)}。`,`总线索净变化 ${signed(leadDelta)}；同时存在其他渠道的增减抵消。`,leadDelta===0?'净增量为零，贡献率不适用。':`最大正向渠道占净增量绝对值 ${pct(contrib)}。`,'核对模拟活动记录，区分规模扩张与客群变化，再设计小范围对照验证。'],['P1','趋势','把观察固化为下期验收项',`本周订单 ${fmt(week.orders)}，环比 ${deltaText(week.orders,oldWeek.orders)}。`,'短期波动需要结合连续趋势与完整统计窗口。',`MTD 订单变化 ${signed(orderDelta)}；当周变化 ${signed(week.orders-oldWeek.orders)}，不混用两个窗口。`,'下一期复查同一组指标、渠道与口径，记录假设得到支持、被否定或仍缺证据。']];
content.innerHTML+=section(5,'结论与行动',notes('将前四部分的发现收敛为有优先级的验证动作。','明确区分数据事实、模拟记录与待验证解释；不把相关性当成因果。'),actions.map(([p,c,t,a,b,d,e])=>`<article class="action"><h3><span class="tag">${p}</span><span class="tag category">${c}</span>${t}</h3><dl><dt>结论</dt><dd>${a}</dd><dt>判断依据</dt><dd>${b}</dd><dt>量化影响</dt><dd>${d}</dd><dt>建议动作</dt><dd>${e}</dd></dl></article>`).join(''));
}
init();

