const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],reduced=matchMedia('(prefers-reduced-motion: reduce)');
const hero=$('.poster');if(matchMedia('(hover:hover) and (pointer:fine)').matches&&!reduced.matches){hero.addEventListener('pointermove',e=>{const r=hero.getBoundingClientRect();hero.style.setProperty('--px',`${(e.clientX/r.width-.5)*16}px`);hero.style.setProperty('--py',`${((e.clientY-r.top)/r.height-.5)*16}px`)});hero.addEventListener('pointerleave',()=>{hero.style.setProperty('--px','0px');hero.style.setProperty('--py','0px')})}
const io=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){$$('.work-nav>div>a').forEach(a=>{const active=a.hash==='#'+e.target.id;a.classList.toggle('active',active);active?a.setAttribute('aria-current','location'):a.removeAttribute('aria-current')});if(!reduced.matches)e.target.querySelector('.case-heading')?.classList.add('reveal')}})},{rootMargin:'-10% 0px -55%'});$$('[data-project]').forEach(e=>io.observe(e));
const dialog=$('#image-dialog');let trigger;$$('[data-image]').forEach(b=>b.addEventListener('click',()=>{trigger=b;$('#full-image').src=b.dataset.image;$('#full-image').alt=b.dataset.caption;$('#image-caption').textContent=b.dataset.caption;dialog.showModal();document.body.style.overflow='hidden'}));$('#close-image').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>{document.body.style.overflow='';$('#full-image').removeAttribute('src');trigger?.focus({preventScroll:true})});
function tabsKeyboard(list,select){list.forEach((b,i)=>b.addEventListener('keydown',e=>{let k;if(e.key==='ArrowRight'||e.key==='ArrowDown')k=(i+1)%list.length;if(e.key==='ArrowLeft'||e.key==='ArrowUp')k=(i-1+list.length)%list.length;if(e.key==='Home')k=0;if(e.key==='End')k=list.length-1;if(k!==undefined){e.preventDefault();select(k);list[k].focus()}}))}
$$('.page-deck').forEach((deck,n)=>{const tabs=[...deck.querySelectorAll('[role=tab]')],panels=[...deck.querySelectorAll('[role=tabpanel]')];const select=i=>{tabs.forEach((b,j)=>{b.setAttribute('aria-selected',i===j);b.tabIndex=i===j?0:-1;panels[j].hidden=i!==j})};tabs.forEach((b,i)=>{b.id=`deck-${n}-tab-${i}`;b.setAttribute('aria-controls',`deck-${n}-panel-${i}`);panels[i].id=`deck-${n}-panel-${i}`;panels[i].setAttribute('aria-labelledby',b.id);b.onclick=()=>select(i)});tabsKeyboard(tabs,select);select(0)});
const flow=[`<span class="eyebrow">01 / DEFINE THE QUESTION</span><h4>“线索涨了，为什么订单没跟上？”</h4><div class="flow-example">虚构场景：知屿体验服务 · 周度经营复盘</div><div class="flow-grid"><article><h5>规模</h5><p>变化集中在哪个指标？周度与 MTD 是否一致？</p></article><article><h5>结构</h5><p>哪些渠道贡献增长，哪些渠道产生抵消？</p></article><article><h5>转化</h5><p>预约、到场、购买，断点出现在哪一步？</p></article><article><h5>趋势</h5><p>是单周波动，还是连续多周的变化？</p></article></div><small>沉淀：可复用的问题清单与分析维度。</small>`,
`<span class="eyebrow">02 / STRUCTURE THE KNOWLEDGE</span><h4>把模糊描述，固定为共同口径。</h4><div class="flow-grid"><article><h5>指标字典</h5><p>到场购买率 = 购买数 ÷ 到场数<br>使用同一统计周期与数据范围。</p></article><article><h5>日期规则</h5><p>周度：完整周 vs 前一完整周<br>MTD：月初至截止日 vs 上月同期。</p></article><article><h5>渠道结构</h5><p>线上 / 线下 → 来源渠道 → 活动记录<br>统一命名，保留可追溯关系。</p></article><article><h5>边界规则</h5><p>缺数 ≠ 零；比例变化用百分点。<br>贡献超过 100% 时解释其他项抵消。</p></article></div><small>沉淀：指标字典、知识条目、输出模板与异常处理规则。</small>`,
`<span class="eyebrow">03 / EXECUTE THE CHAIN</span><h4>每一步有输入，也有验收标准。</h4><div class="task-sequence"><span><b>01</b>取数校验：日期、字段、完整性</span><span><b>02</b>波动计算：绝对量、变化率、百分点</span><span><b>03</b>贡献拆解：渠道增量与抵消项</span><span><b>04</b>证据匹配：活动记录与待验证假设</span><span><b>05</b>报告输出：结论、依据与行动建议</span></div><small>沉淀：任务拆分、输入输出规范与逐步检查清单。</small>`,
`<span class="eyebrow">04 / VALIDATE & ITERATE</span><h4>让一次反馈，变成下一次的规则。</h4><ul class="flow-checks"><li><b>✓</b>数字校验：表格、图表与结论使用同一计算结果。</li><li><b>✓</b>语义校验：升降方向、日期与分母一致。</li><li><b>✓</b>证据校验：区分已知记录、解释假设与因果证据。</li><li><b>↻</b>迭代示例：发现“贡献率 >100%”被误判 → 增加抵消项解释规则 → 用案例回归检查。</li></ul><small>沉淀：错误类型、验收案例、版本记录与可复用技能规范。</small>`];
const ft=$$('[data-flow]');function showFlow(i){$('#flow-display').innerHTML=flow[i];ft.forEach((b,j)=>{b.setAttribute('aria-selected',i===j);b.setAttribute('aria-controls','flow-display');b.id='flow-tab-'+j;b.tabIndex=i===j?0:-1});$('#flow-display').setAttribute('aria-labelledby','flow-tab-'+i)}ft.forEach((b,i)=>b.onclick=()=>showFlow(i));tabsKeyboard(ft,showFlow);showFlow(0);
const nodeCopy=['需求问卷 → 人员与柜台 / 工服主数据：按场景收集需求，辅助匹配岗位、款式与寄送信息。','人员与柜台 → 需求问卷 / 工服主数据：统一人员、岗位和地址信息，减少重复填写与人工核验。','工服主数据 → 需求问卷 / 库存与成本：统一 SKU、尺码与款式关系，为推荐和计算提供基础。','库存与成本 → 工服主数据 / 系统仪表盘：联动订购记录与库存，汇总数量及金额，支持监控。','系统仪表盘 ← 库存与成本 / 需求问卷：呈现订购结构与月度变化，为复盘提供统一视图。'];const relations=[[1,2],[0,2],[0,3],[2,4],[0,3]];const nodes=$$('[data-node]');function selectNode(i){nodes.forEach((b,j)=>{b.setAttribute('aria-pressed',j===i);b.classList.toggle('related',relations[i].includes(j))});$('#system-description').textContent=nodeCopy[i]}nodes.forEach((b,i)=>{b.onclick=()=>selectNode(i);b.addEventListener('mouseenter',()=>{if(matchMedia('(hover:hover)').matches)selectNode(i)})});selectNode(0);
let article=0;const cards=$$('[data-article]'),gallery=$('.arc-gallery'),mobile=matchMedia('(max-width:700px)');function showArticle(i,scroll=true){article=(i+cards.length)%cards.length;cards.forEach((c,j)=>{let d=j-article;if(d>2)d-=5;if(d< -2)d+=5;c.style.setProperty('--offset',d);c.style.setProperty('--abs',Math.abs(d));c.style.setProperty('--layer',5-Math.abs(d));c.classList.toggle('current',j===article);j===article?c.setAttribute('aria-current','true'):c.removeAttribute('aria-current')});$('#article-count').textContent=`0${article+1} / 05`;if(mobile.matches&&scroll)gallery.scrollTo({left:cards[article].offsetLeft-(gallery.clientWidth-cards[article].offsetWidth)/2,behavior:reduced.matches?'instant':'smooth'})}$$('[data-gallery-step]').forEach(b=>b.onclick=()=>showArticle(article+Number(b.dataset.galleryStep)));showArticle(0,false);
let photo=0;const photos=$$('[data-photo]');function showPhoto(i){photo=(i+photos.length)%photos.length;photos.forEach((p,j)=>{const d=(j-photo+photos.length)%photos.length;p.style.setProperty('--photo-offset',d<3?d:0);p.style.setProperty('--photo-layer',6-d);p.style.setProperty('--photo-opacity',d<3?1:0);p.setAttribute('aria-hidden',d!==0)});$('#photo-count').textContent=`0${photo+1} / 0${photos.length}`}$$('[data-photo-step]').forEach(b=>b.onclick=()=>showPhoto(photo+Number(b.dataset.photoStep)));showPhoto(0);
function swipe(el,fn){let start=null,dragged=false;el.addEventListener('pointerdown',e=>{start=e.clientX;dragged=false});el.addEventListener('pointerup',e=>{if(start!==null&&Math.abs(e.clientX-start)>45){dragged=true;fn(e.clientX<start?1:-1)}start=null});el.addEventListener('pointercancel',()=>start=null);el.addEventListener('click',e=>{if(dragged){e.preventDefault();dragged=false}},true);el.addEventListener('dragstart',e=>e.preventDefault())}swipe(gallery,d=>{if(!mobile.matches)showArticle(article+d)});swipe($('.photo-stack'),d=>showPhoto(photo+d));let scrollTimer;gallery.addEventListener('scroll',()=>{if(!mobile.matches)return;clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>{const x=gallery.scrollLeft+gallery.clientWidth/2;let i=0,dist=Infinity;cards.forEach((c,j)=>{const d=Math.abs(c.offsetLeft+c.offsetWidth/2-x);if(d<dist){dist=d;i=j}});showArticle(i,false)},120)});
const resize=new ResizeObserver(es=>es.forEach(({target,contentRect})=>{const frame=target.querySelector('iframe'),width=target.classList.contains('report-window')?1000:500;frame.style.width=width+'px';frame.style.transform='scale('+contentRect.width/width+')'}));$$('.prototype-window,.report-window').forEach(p=>resize.observe(p));
