(() => {
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const data = {
    vegetables:[['broccoli','🥦'],['potato','🥔'],['onion','🧅'],['tomato','🍅'],['carrot','🥕'],['spinach','🥬']],
    meat:[['chicken','🍗'],['tofu','◻️'],['salmon','🐟'],['egg','🥚'],['beef','🥩'],['shrimp','🦐']],
    carbs:[['rice','🍚'],['noodles','🍜'],['bread','🍞'],['pasta','🍝'],['oats','🥣'],['sweet potato','🍠']],
    other:[['mushroom','🍄'],['garlic','🧄'],['chili','🌶️'],['lemon','🍋'],['yogurt','🥛'],['herbs','🌿']]
  };
  const recipes = [
    {id:'sichuan-chicken',name:'Sichuan Pepper Chicken Thigh with Veggies',vibe:'Quick & Easy · Chill Night',tags:['High Protein','Mild Spicy','15 min'],desc:'Crisp vegetables, tender chicken and a bright pepper finish.',ings:['chicken','broccoli','onion','carrot'],pod:'Sichuan Pepper · Bright Chili',steps:['Sear chicken until golden.','Toss in vegetables and cook until crisp.','Finish with your Flavor Pod and serve.']},
    {id:'tofu-stirfry',name:'Tofu Veggie Stir-Fry',vibe:'Fresh · Light afternoon',tags:['Low Calorie','Veggie','15 min'],desc:'Fresh, bright energy for a light and easy evening.',ings:['tofu','broccoli','carrot','spinach'],pod:'Lemon Sea Salt · Herb Pepper',steps:['Crisp tofu in a warm pan.','Add vegetables with a splash of water.','Press in the pod just before serving.']},
    {id:'salmon-bowl',name:'Green Salmon Grain Bowl',vibe:'Post Workout · Clean fuel',tags:['High Protein','Balanced','20 min'],desc:'A gently savory bowl with greens, grains and citrus.',ings:['salmon','rice','spinach','lemon'],pod:'Yuzu Miso · Garden Herb',steps:['Cook the rice and pan-sear the salmon.','Build the bowl with greens.','Add the pod and a squeeze of lemon.']},
    {id:'tomato-pasta',name:'Tomato Cloud Pasta',vibe:'Cozy · Savory',tags:['Comfort','Veggie','18 min'],desc:'Silky tomato pasta with a lifted herb finish.',ings:['pasta','tomato','garlic','herbs'],pod:'Tomato Umami · Basil',steps:['Boil pasta until just tender.','Warm tomato, garlic and herbs.','Toss together with the pod.']}
  ];
  const pods = [{name:'Lemon Sea Salt',color:'#eac85b'},{name:'Herb Pepper',color:'#6b9c74'},{name:'Bright Chili',color:'#e87555'},{name:'Yuzu Miso',color:'#f3a93d'},{name:'Garden Herb',color:'#9cc77c'},{name:'Smoky Sesame',color:'#97785c'}];
  const state={cat:'vegetables',selected:new Set(),cart:read('fm-cart',[]),cube:read('fm-cube',Array.from({length:27},(_,i)=>pods[i%pods.length].name)),chosenPod:pods[0].name,recipe:recipes[0],goal:0,day:0,macro:'balanced',rotation:-26};
  const plans=[{name:'Fat reduction & body shaping',kcal:1650,macro:[35,40,25],meals:[['Egg & greens toast','430'],['Chicken veggie bowl','610'],['Yogurt and berries','330']]},{name:'Build strength',kcal:2050,macro:[40,35,25],meals:[['Protein oats','510'],['Salmon grain bowl','710'],['Tofu noodles','540']]},{name:'Balanced energy',kcal:1850,macro:[30,45,25],meals:[['Fruit yogurt bowl','420'],['Tomato cloud pasta','650'],['Herb chicken salad','430']]},{name:'Maintain my rhythm',kcal:1750,macro:[30,40,30],meals:[['Avocado egg toast','460'],['Bright veggie rice','630'],['Miso salmon soup','370']]}];
  function read(key, fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
  function write(key,val){localStorage.setItem(key,JSON.stringify(val))}
  function route(value, replace=false){location.hash=value.startsWith('#')?value:'#'+value;if(replace) renderRoute()}
  function renderRoute(){const path=location.hash.slice(1)||'home';const [view,sub]=path.split('/');$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('.tabbar button').forEach(x=>x.classList.toggle('active',x.dataset.route.split('/')[0]===view));if(view==='flavor') switchFlavor(sub||'shaker');if(view==='recipe') renderDetail();$('.views').scrollTop=0;}
  function icon(name){return (data[state.cat].find(x=>x[0]===name)||Object.values(data).flat().find(x=>x[0]===name)||['','✦'])[1]}
  function title(name){return name.replace(/\b\w/g,x=>x.toUpperCase())}
  function renderIngredients(){const catLabels={vegetables:'Veggies 🥦',meat:'Meat 🍗',carbs:'Carbs 🍚',other:'Other 🧂'};$('#categories').innerHTML=Object.keys(data).map(c=>`<button class="${c===state.cat?'active':''}" data-cat="${c}">${catLabels[c]}</button>`).join('');$('#ingredients').innerHTML=data[state.cat].map(([name,emoji])=>`<button class="ingredient ${state.selected.has(name)?'selected':''}" data-ingredient="${name}"><i>${emoji}</i><span>${title(name)}</span></button>`).join('');$('#selected-count').textContent=state.selected.size;$('#generate').disabled=!state.selected.size;}
  function matchRecipes(){const ranked=recipes.map(r=>({...r,score:r.ings.filter(i=>state.selected.has(i)).length})).sort((a,b)=>b.score-a.score);$('#matches').innerHTML=ranked.slice(0,3).map(r=>`<button class="match-card" data-recipe="${r.id}"><span>${r.vibe}</span><b>${r.name}</b><small>${r.tags.join(' · ')} <i>→</i></small></button>`).join('');openSheet('match-sheet')}
  function renderDetail(){const r=state.recipe;const on=r.ings.filter(i=>state.selected.has(i));const pickup=r.ings.filter(i=>!state.selected.has(i));$('#recipe-detail').innerHTML=`<span class="recipe-vibe">${r.vibe}</span><h1>${r.name}</h1><div class="recipe-tags">${r.tags.map(t=>`<span>${t}</span>`).join('')}</div><p>${r.desc}</p><h3>Ingredients</h3><p>${r.ings.map(title).join(', ')}</p><div class="on-hand"><p><b>On hand</b>${on.length?on.map(title).join(', '):'Pick an ingredient to personalise this.'}</p><p><b>To pick up</b>${pickup.map(title).join(', ')}</p></div><h3>Make it yours</h3><p>${r.pod}</p><h3>Let's cook</h3><ol>${r.steps.map(s=>`<li>${s}</li>`).join('')}</ol><button class="outline save-recipe">♡ Save recipe</button><button class="primary add-recipe">Add meal &amp; pods</button>`}
  function renderLight(){const p=plans[state.goal], m=state.macro==='protein'?[45,30,25]:p.macro;$('#goal-name').textContent=p.name;$('#calories').textContent=p.kcal;$('#calorie-bar').style.width=(p.kcal/24)+'%';[['p',m[0]],['c',m[1]],['f',m[2]]].forEach(([k,v])=>{$('#macro-'+k).style.width=v+'%';$('#macro-'+k).textContent=v+'%';$('#legend-'+k).textContent=v+'%'});$$('[data-macro]').forEach(x=>x.classList.toggle('active',x.dataset.macro===state.macro));const ds=['M','T','W','T','F','S','S'];$('#week').innerHTML=ds.map((d,i)=>`<button class="${i===state.day?'active':''}" data-day="${i}"><small>${d}</small><b>${15+i}</b></button>`).join('');const meals=p.meals;$('#day-card').innerHTML=`<h2>${['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][state.day]} <span>Today</span></h2>${meals.map((m,i)=>`<p><small>${['BREAKFAST','LUNCH','DINNER'][i]}</small><b>${m[0]}</b><span>${m[1]} kcal</span></p>`).join('')}`}
  function switchFlavor(panel){$$('[data-flavor]').forEach(x=>x.classList.toggle('active',x.dataset.flavor===panel));$$('.flavor-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===panel));}
  function shake(){const a=['INTJ','ENFP','ISFP','ENTP'],b=['Fresh','Savory','Spicy','Cozy'],c=['Chill Night','Post Workout','Quick & Easy','Sunny Lunch'];const reel=[$('#reel-a'),$('#reel-b'),$('#reel-c')];$('#shake').disabled=true;$('#shake').textContent='SHAKING…';reel.forEach((el,i)=>{el.classList.add('spinning');let n=0;const timer=setInterval(()=>{el.textContent=[a,b,c][i][n++%4]},75);setTimeout(()=>{clearInterval(timer);el.textContent=[a,b,c][i][Math.floor(Math.random()*4)];el.classList.remove('spinning');if(i===2){state.recipe=recipes[Math.floor(Math.random()*recipes.length)];renderShaken();$('#shake').disabled=false;$('#shake').textContent='SHAKE AGAIN'}},900+i*450)})}
  function renderShaken(){const r=state.recipe;const el=$('#shaken-recipe');el.hidden=false;el.innerHTML=`<span>${r.vibe}</span><h2>${r.name}</h2><div class="recipe-tags">${r.tags.map(t=>`<span>${t}</span>`).join('')}</div><p>${r.desc}</p><button class="view-recipe">View full recipe →</button><div class="shaken-cube"><small>YOUR CUSTOM FLAVOR CUBE</small><b>${r.pod}</b></div><button class="primary add-recipe">Add meal &amp; pods</button><div class="shake-options"><button class="alternative">Try another</button><button class="reshake">Shake again</button></div>`}
  const podSymbols = {'Lemon Sea Salt':'🍋','Herb Pepper':'🌿','Bright Chili':'🌶️','Yuzu Miso':'🍊','Garden Herb':'🥬','Smoky Sesame':'🥜'};
  let cubeLayer = 'all';
  function renderCube(){
    const faces=['front','back','right','left','top','bottom'];
    const cubies=[];
    for(let z=0;z<3;z++) for(let y=0;y<3;y++) for(let x=0;x<3;x++){
      const idx=z*9+y*3+x, name=state.cube[idx]||pods[0].name;
      if(cubeLayer!=='all' && z!==Number(cubeLayer)) continue;
      const glyph=podSymbols[name]||'🌿';
      cubies.push(`<div class="storage-cubie" style="transform:translate3d(${(x-1)*52}px,${(y-1)*52}px,${(1-z)*52}px)">${faces.map(face=>`<button class="cube-cell storage-face ${face}" draggable="true" data-index="${idx}" aria-label="Compartment ${idx+1}: ${name}" title="${idx+1} · ${name}"><span class="compartment-number">${idx+1}</span><span class="compartment-ingredient">${glyph}</span></button>`).join('')}</div>`);
    }
    $('#cube-3d').innerHTML=cubies.join('');
    $('#cube-3d').style.transform=`rotateX(-22deg) rotateY(${state.rotation}deg)`;
    $('#pods').innerHTML=pods.map(p=>`<button class="pod-choice ${p.name===state.chosenPod?'selected':''}" data-pod="${p.name}" aria-pressed="${p.name===state.chosenPod}"><span class="pod-food-icon">${podSymbols[p.name]}</span>${p.name}</button>`).join('');
    const variety=new Set(state.cube).size;
    $('#cube-price').textContent='¥'+(26.4+state.cube.filter(Boolean).length*1.5).toFixed(1);
    $('#cube-balance').textContent=variety>=5?'Bright & savory':'Needs more contrast';
    $('#cube-note').textContent=variety>=5?'A balanced mix: bright notes, warmth, and a savory finish.':'Try a second flavor family to give your cube more dimension.';
    write('fm-cube',state.cube);
  }
  $('#cube-layer').addEventListener('change',e=>{cubeLayer=e.target.value;renderCube()});
  function renderStats(){const mixes=read('fm-mixes',[]), orders=read('fm-orders',[]);$('#mixes-stat').textContent=mixes.length;$('#orders-stat').textContent=orders.length;}
  function updateCart(){write('fm-cart',state.cart);const amount=state.cart.length;$$('.cart-badge').forEach(x=>{x.hidden=!amount;x.textContent=amount});$('#cart-items').innerHTML=amount?state.cart.map((item,i)=>`<div class="cart-item"><span>${item.name}</span><b>¥${item.price}</b><button data-remove="${i}">×</button></div>`).join(''):'<p class="empty">Your bag is ready for something delicious.</p>';$('#cart-total').textContent='¥'+state.cart.reduce((s,x)=>s+x.price,0).toFixed(1)}
  function addCart(name,price){state.cart.push({name,price:Number(price)});updateCart();toast('Added to your bag')}
  function openSheet(id){$('.overlay').hidden=false;$('#'+id).hidden=false}
  function closeSheets(){$$('.sheet').forEach(x=>x.hidden=true);$('.overlay').hidden=true}
  function toast(message){const t=$('#toast');t.textContent=message;t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,2200)}
  function mePanel(type){const saved=read('fm-favorites',[]),mixes=read('fm-mixes',[]),orders=read('fm-orders',[]);let html='';if(type==='orders')html=`<h2>My Orders</h2>${orders.length?orders.map(o=>`<article class="saved"><b>${o.name}</b><span>¥${o.price} · Demo order</span></article>`).join(''):'<p class="empty">No demo orders yet.</p>'}`;if(type==='mixes')html=`<h2>Saved Flavor Cubes</h2>${mixes.length?mixes.map(m=>`<article class="saved"><b>${m.name}</b><span>${m.cube.length} capsules</span></article>`).join(''):'<p class="empty">Your saved cubes will appear here.</p>'}`;if(type==='favorites')html=`<h2>Saved Recipes</h2>${saved.length?saved.map(id=>`<article class="saved"><b>${recipes.find(r=>r.id===id)?.name||id}</b></article>`).join(''):'<p class="empty">Save a recipe to keep it here.</p>'}`;if(type==='address')html='<h2>Delivery Address</h2><p class="empty">Add an address when this concept becomes a real service.</p>';if(type==='preferences')html='<h2>Preferences</h2><article class="saved"><b>Vegetarian friendly</b><span>Off</span></article><article class="saved"><b>Gentle spice</b><span>On</span></article>';if(type==='language')html='<h2>Language</h2><article class="saved"><b>English</b><span>Selected</span></article><article class="saved"><b>中文</b><span>Coming soon</span></article>';$('#me-content').innerHTML=html;openSheet('me-sheet')}
  document.addEventListener('click',e=>{const routeBtn=e.target.closest('[data-route]');if(routeBtn){route(routeBtn.dataset.route);return}const cat=e.target.closest('[data-cat]');if(cat){state.cat=cat.dataset.cat;renderIngredients();return}const ing=e.target.closest('[data-ingredient]');if(ing){const n=ing.dataset.ingredient;state.selected.has(n)?state.selected.delete(n):state.selected.add(n);renderIngredients();return}const rec=e.target.closest('[data-recipe]');if(rec){state.recipe=recipes.find(r=>r.id===rec.dataset.recipe);closeSheets();route('recipe');return}if(e.target.closest('[data-open-cart]')){openSheet('cart-sheet');return}if(e.target.closest('[data-close]')||e.target===$('.overlay')){closeSheets();return}const remove=e.target.closest('[data-remove]');if(remove){state.cart.splice(Number(remove.dataset.remove),1);updateCart();return}const add=e.target.closest('[data-add]');if(add){addCart(add.dataset.add,add.dataset.price);return}const flavor=e.target.closest('[data-flavor]');if(flavor){switchFlavor(flavor.dataset.flavor);route('flavor/'+flavor.dataset.flavor);return}const pod=e.target.closest('[data-pod]');if(pod){state.chosenPod=pod.dataset.pod;renderCube();return}const cell=e.target.closest('.cube-cell');if(cell){state.cube[Number(cell.dataset.index)]=state.chosenPod;renderCube();return}const me=e.target.closest('[data-me]');if(me){mePanel(me.dataset.me);return}if(e.target.closest('.view-recipe')){route('recipe');return}if(e.target.closest('.add-recipe')){addCart(state.recipe.name+' + Flavor Pod',69);return}if(e.target.closest('.alternative')){state.recipe=recipes[(recipes.indexOf(state.recipe)+1)%recipes.length];renderShaken();return}if(e.target.closest('.reshake')){shake();return}if(e.target.closest('.save-recipe')){const saved=read('fm-favorites',[]);if(!saved.includes(state.recipe.id))saved.push(state.recipe.id);write('fm-favorites',saved);toast('Recipe saved');return}});
  $('#generate').addEventListener('click',matchRecipes);$('#change-goal').addEventListener('click',()=>{state.goal=(state.goal+1)%plans.length;renderLight();toast('Goal updated')});$$('[data-macro]').forEach(x=>x.addEventListener('click',()=>{state.macro=x.dataset.macro;renderLight()}));$('#week').addEventListener('click',e=>{const b=e.target.closest('[data-day]');if(b){state.day=Number(b.dataset.day);renderLight()}});$('#shake').addEventListener('click',shake);$('#lever').addEventListener('click',shake);$('#cube-left').addEventListener('click',()=>{state.rotation-=90;renderCube()});$('#cube-right').addEventListener('click',()=>{state.rotation+=90;renderCube()});$('#save-cube').addEventListener('click',()=>{const mixes=read('fm-mixes',[]);mixes.unshift({name:$('#cube-name').value.trim()||'My Flavor Cube',cube:[...state.cube]});write('fm-mixes',mixes);renderStats();toast('Flavor Cube saved')});$('#share-cube').addEventListener('click',async()=>{const url=location.origin+location.pathname+'#flavor/cube';try{await navigator.clipboard.writeText(url);toast('Share link copied')}catch{toast('Your cube is ready to share')}});$('#add-cube').addEventListener('click',()=>addCart($('#cube-name').value.trim()||'My Flavor Cube',39.9));$('#checkout').addEventListener('click',()=>{if(!state.cart.length)return toast('Your bag is empty');const orders=read('fm-orders',[]);orders.unshift(...state.cart);write('fm-orders',orders);state.cart=[];updateCart();renderStats();closeSheets();toast('Demo order placed ✦')});
  let dragIndex=null;$('#cube-3d').addEventListener('dragstart',e=>{const cell=e.target.closest('.cube-cell');if(cell)dragIndex=Number(cell.dataset.index)});$('#cube-3d').addEventListener('dragover',e=>e.preventDefault());$('#cube-3d').addEventListener('drop',e=>{const cell=e.target.closest('.cube-cell');if(cell&&dragIndex!==null){const to=Number(cell.dataset.index);[state.cube[dragIndex],state.cube[to]]=[state.cube[to],state.cube[dragIndex]];dragIndex=null;renderCube()}});
  window.addEventListener('hashchange',renderRoute);renderIngredients();renderLight();renderCube();renderStats();updateCart();renderRoute();
})();
